"""Events package for the observer pattern.

This package provides the event types, observer protocol, and collector
for the effects system. Templates emit events through an EffectsCollector,
which notifies observers that collect and process the events.
"""

from mudd.events.collector import EffectsCollector
from mudd.events.observer import Observer
from mudd.events.types import (
    BalanceChangedEvent,
    BroadcastEvent,
    ChargeCurrencySignal,
    ClearFocusSignal,
    DestroySignal,
    DialogSessionEndedEvent,
    DialogSignal,
    DialogStartedEvent,
    DispenseSignal,
    DropSignal,
    EntityDestroyedEvent,
    EntityDroppedEvent,
    EntityPickedUpEvent,
    FocusChangedEvent,
    GameEvent,
    GrantCurrencyEvent,
    GrantEvent,
    GrantRandomEvent,
    GrantXPSignal,
    InventorySyncEvent,
    LevelUpEvent,
    OrphanChannelDetectedEvent,
    PickupSignal,
    RoomSyncedEvent,
    SetFocusSignal,
    ShopSignal,
    TradingSessionEndedEvent,
    TradingSessionStartedEvent,
    UserJoinedEvent,
    UserLeftEvent,
    UserLocationSyncEvent,
    UserMovedEvent,
    UserSyncEvent,
    XPGainedEvent,
    ZoneSyncedEvent,
)

__all__ = [
    # Collector
    "EffectsCollector",
    # Observer protocols
    "Observer",
    # Event types
    "GameEvent",
    "BroadcastEvent",
    "GrantEvent",
    "GrantRandomEvent",
    "GrantCurrencyEvent",
    "ChargeCurrencySignal",
    "GrantXPSignal",
    "PickupSignal",
    "DropSignal",
    "DestroySignal",
    "DispenseSignal",
    "SetFocusSignal",
    "ClearFocusSignal",
    "ShopSignal",
    "DialogSignal",
    "TradingSessionStartedEvent",
    "TradingSessionEndedEvent",
    "DialogStartedEvent",
    "DialogSessionEndedEvent",
    "EntityPickedUpEvent",
    "EntityDroppedEvent",
    "EntityDestroyedEvent",
    "FocusChangedEvent",
    "XPGainedEvent",
    "LevelUpEvent",
    "ZoneSyncedEvent",
    "RoomSyncedEvent",
    "OrphanChannelDetectedEvent",
    "BalanceChangedEvent",
    "InventorySyncEvent",
    "UserMovedEvent",
    "UserLocationSyncEvent",
    "UserSyncEvent",
    "UserJoinedEvent",
    "UserLeftEvent",
]
